### ISSUE TITLE
VSCode fails to jump with ctrl+click on `file://` urls

### ISSUE THREAD

**Issue by STRd6** [DanielXMoore/Civet#1028]
Ctrl Clicking these location outputs in the console fails to jump to them.

```
ReferenceError: gatherRecursive is not defined
    at processBlocks (file:///home/daniel/apps/civet/source/parser/block.civet:143:3)
    at processProgram (file:///home/daniel/apps/civet/source/parser/lib.civet:1362:3)
    at file:///home/daniel/apps/civet/source/parser.hera:1069:1
    at /home/daniel/apps/civet/node_modules/@danielx/hera/dist/machine.js:270:25
    at $EVENT (/home/daniel/apps/civet/node_modules/@danielx/hera/dist/machine.js:314:16)
 ```

It works if we remove `file://`

**Comment by edemaine** [comment]
Could that be a bug in your split branch? Maybe `block.civet` needs to import `gatherRecursive` from `lib.civet`?

**Comment by STRd6** [comment]
It's not the specific error, just that the link doesn't navigate in VSCode.

**Comment by STRd6** [comment]
Seems to be working fine these days, the source urls are showing up as relative now.
