### ISSUE TITLE
ESM loader (and tests) fail on Node 20

### ISSUE THREAD

**Issue by bbrk24** [DanielXMoore/Civet#798]
On node 18 (v18.18.2), the tests run just fine. However, on node 20 (v20.9.0), it fails with a parse error on the very first character of parser.hera:

```
/home/bbrk24/workspace/Civet/source/parser.hera:1
# Civet: A successor to CoffeeScript and alternative to TypeScript
^

SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1153:20)
    at Module._compile (node:internal/modules/cjs/loader:1205:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at cjsLoader (node:internal/modules/esm/translators:284:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:234:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:431:15)
    at async formattedImport (/home/bbrk24/workspace/Civet/node_modules/mocha/lib/nodejs/esm-utils.js:9:14)
    at async exports.requireOrImport (/home/bbrk24/workspace/Civet/node_modules/mocha/lib/nodejs/esm-utils.js:42:28)
    at async exports.loadFilesAsync (/home/bbrk24/workspace/Civet/node_modules/mocha/lib/nodejs/esm-utils.js:100:20)
    at async singleRun (/home/bbrk24/workspace/Civet/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async exports.handler (/home/bbrk24/workspace/Civet/node_modules/mocha/lib/cli/run.js:370:5)
```

`yarn build` works fine on both node versions. Only `yarn test` exhibits this behavior.

**Comment by STRd6** [comment]
It's also broken on node 18.19 now as well 🙀

**Comment by STRd6** [comment]
Some resources:

- https://nodejs.org/api/module.html#customization-hooks

**Comment by STRd6** [comment]
@edemaine I've started a bit on this from the Hera side.

Here's my overall plan:
- Extend Hera to emit ESM in addition to CJS
- Update `parser.hera` in Civet to use ESM imports
- Update `lib.civet` to use ESM exports
- Drop `ts-node` as a dev dep in Civet
- Update the `build/` Civet/Hera esm loaders

There's probably some additional work to get things to work in both Node `18.<19` and `18.19+, 20` and debugging the loaders isn't any easier in the newer node versions.

There might also be a some quick tricks to get things to work in the meantime but I haven't found them yet. Hopefully I can make some good progress today but I'm not sure how much time I'll have this week.

**Comment by edemaine** [comment]
Wow, that's a lot more than I expected!

I guess for end users (not developers building/testing Civet), we can just do the last bullet?  So that might make it highest priority.  (Until the other bullets, we can use older Nodes to build and test.)

For CJS: did you try `--experimental-specifier-resolution=node`? Apparently this restores some CJS features like automatic extension resolution.

**Comment by STRd6** [comment]
Fixed in https://github.com/DanielXMoore/Civet/pull/942

**Comment by edemaine** [comment]
I feel like there's still work to be done here, in `source/esm.civet`. Node 20.11.1 now gives the following warning (during `yarn test` and e.g. `civet foo.civet` when `foo.civet` uses `import`):

> (node:27300) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("%40danielx/civet/esm", pathToFileURL("./"));'

It does work, but we should probably update to provide an easy `register` mechanism that follows the new API.
